services:
  bot:
    image: bestbot:local
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - discord-net

volumes:
  bot_data:
    driver: local

networks:
  discord-net: